```{r}
library(tidyverse)
library(data.table)
library(gtfsrealtime)
library(gtfstools)
library(ggunc)
```

```{r}
DATA_PATH = Sys.getenv("DATA_PATH")
```

```{r}
stop_times = lapply(Sys.glob(file.path(DATA_PATH, "gotriangle/static/*.zip")), function(filename) {
  gtfs = read_gtfs(filename)
  gtfs$stop_times$service_day_start = ymd(filename)
  gtfs$stops[,.(stop_id, stop_lat, stop_lon)][gtfs$stop_times, on = .(stop_id)]
}) |>
  rbindlist()

# we don't have static data going all the way back, just use the first we have
stop_times[service_day_start == ymd("2026-01-23"), service_day_start := ymd("2026-01-01")]
```

```{r}
positions = map(
  Sys.glob(file.path(DATA_PATH, "gotriangle/2026/03/*/vehicle-positions/*")),
  function(filename) {
    # TODO use gtfsrt file time stamp
    timestamp = as.POSIXct(
      as.numeric(str_extract(filename, "([0-9]+)\\.pb", 1)),
      timezone = "America/New_York"
    )
    pos = read_gtfsrt_positions(filename, "America/New_York")

    if (nrow(pos) > 0) {
      pos$file_timestamp = timestamp
    }

    pos
  },
  .progress = TRUE
) |>
  rbindlist(fill = TRUE)
```

```{r}
# get the date of the preceding 3am
get_service_day = function(timestamp) {
  as.Date(ifelse(
    hour(timestamp) >= 3,
    date(timestamp),
    date(timestamp) - 1
  ))
}
```

```{r}
positions = positions[, .SD[1], by = c("timestamp", "vehicle_id")]

# compare when in_transit_to changes and when stop ids change. if it actually means after departing
# the stop identified by stop_id, as suggested by the spec, the stop_id will change when switching from IN_TRANSIT_TO
# to to ARRIVING_AT. But if it means it is in transit _to_ the stop identified by stop ID, as the name would
# suggest and as would make intuitive sense, the stop ID will change when switching from STOPPED_AT to IN_TRANSIT_TO.
# In the GoTriangle feed, the latter is the case
setorder(positions, vehicle_id, timestamp)

View(positions[, .(
  vehicle_id,
  timestamp,
  stop_id,
  current_stop_sequence,
  current_status
)])
```

Assign stop times to previous and next positions reports.
```{r}

# The service day is just the preceding 3am, to make sure we match up
# predictions for the right day
positions[, service_day := get_service_day(timestamp)]

setorder(positions, service_day, trip_id, current_stop_sequence, timestamp)

# We want current_stop_sequence = x to mean the exact moment we arrived at the stop

# IN_TRANSIT_TO means have not arrived at stop yet, so we make the stop sequence smaller -
# we want to find the last IN_TRANSIT_TO this stop (or, if there isn't one, the last STOPPED_AT
# from an earlier stop).

# INCOMING_AT is similar but closer to arrival

# STOPPED_AT means we have arrived at the stop in the past, so add a little

positions[,
  adjusted_stop_sequence := current_stop_sequence +
    fcase(
      current_status == "IN_TRANSIT_TO" , -0.5  ,
      current_status == "INCOMING_AT"   , -0.25 ,
      current_status == "STOPPED_AT"    ,  0.25 ,
      default = NA_real_
    )
]

positions = positions[!is.na(adjusted_stop_sequence), ]

# we match trips with positions by service days
# so we first expand stop times so we have a record of each trip
# for every service day.
# this is a little inefficient b/c not every trip runs on every day, but
# the extras get dropped in the next join
all_service_days = data.table(service_day = unique(positions$service_day))
gtfs_days = data.table(gtfs_date = unique(stop_times$service_day_start))
all_service_days = gtfs_days[
  all_service_days,
  on = .(gtfs_date == service_day),
  roll = TRUE,
  .(service_day = i.service_day, gtfs_date = x.gtfs_date)
]

expanded_stop_times = stop_times[all_service_days, on = .(service_day_start == gtfs_date), allow.cartesian = T]

times = positions[
  expanded_stop_times,
  on = .(service_day, trip_id, adjusted_stop_sequence == stop_sequence),
  roll = TRUE,
  .(
    trip_id,
    prev_stop_sequence = x.adjusted_stop_sequence,
    stop_sequence = i.stop_sequence,
    stop_id = i.stop_id,
    stop_lat,
    stop_lon,
    service_day,
    prev_time = timestamp,
    prev_lat = latitude,
    prev_lon = longitude
  ),
  nomatch = NULL
]

stopifnot(all(times$stop_sequence > times$prev_stop_sequence))
stopifnot(!anyDuplicated(times[, .(service_day, trip_id, stop_sequence)]))

# and now search forward
times = positions[
  times,
  on = .(service_day, trip_id, adjusted_stop_sequence == stop_sequence),
  roll = -Inf,
  .(
    trip_id,
    stop_id = i.stop_id,
    prev_time,
    prev_lat,
    prev_lon,
    stop_lat,
    stop_lon,
    stop_sequence,
    prev_stop_sequence,
    service_day,
    next_lat = latitude,
    next_lon = longitude,
    next_time = timestamp,
    next_stop_sequence = x.adjusted_stop_sequence
  ),
  nomatch = NULL
]

# TODO a few glitches where time runs backwards?
mean(times$next_time > times$prev_time)

# TODO some really big ones
min(times$next_time - times$prev_time)
max(times$next_time - times$prev_time)

times = times[next_time - prev_time > 0 & next_time - prev_time < 130, ]

# interpolate
# spherical approximation
times[, dist_from_prev := sqrt((stop_lat - prev_lat)^2 + ((stop_lon - prev_lon) * cos(stop_lat))^2)]
times[, dist_to_next := sqrt((stop_lat - next_lat)^2 + ((stop_lon - next_lon) * cos(stop_lat))^2)]
# interpolate based on these distances
times[, frac := dist_from_prev / (dist_from_prev + dist_to_next)]
times[, estimated_time := prev_time + (next_time - prev_time) * frac]
```

```{r}
updates = map(
  Sys.glob(file.path(DATA_PATH, "gotriangle/2026/03/*/trip-updates/*")),
  function(filename) {
    # TODO use gtfsrt file time stamp
    timestamp = with_tz(
      ymd_hms(str_extract(filename, "([0-9]+)\\.pb", 1), tz = "Etc/UTC"),
      tz = "America/New_York"
    )
    upd = read_gtfsrt_trip_updates(filename, "America/New_York")

    if (nrow(upd) > 0) {
      upd$file_timestamp = timestamp
      return(upd[,c("stop_id", "arrival_time", "stop_sequence", "trip_id", "file_timestamp")])
    } else {
        return(NULL)
    }
  },
  .progress = TRUE
) |>
  rbindlist(fill = TRUE)
```

```{r}
# we want to get the service day based on the day the predicted service is running,
# not the day we grabbed the file
updates[, service_day := get_service_day(arrival_time)]

# we lose a lot here because the stop sequences don't match perfectly, so match
# on stop id and closest stop sequence
predictions = times[updates, on = .(service_day, trip_id, stop_id, stop_sequence), roll = 'nearest', nomatch = NULL]

predictions[, error := difftime(estimated_time, arrival_time, units = "mins")]
# using predicted rather than actual arrival time, because riders don't
# know the actual arrival time. So if the prediction is e.g. 20 minutes how
# accurate is that?
predictions[, horizon := difftime(arrival_time, file_timestamp, units = "mins")]
predictions[, horizon_cat := cut(as.numeric(horizon), c(0, 10, 15, 20, 30, 60, Inf))]
```

Prediction is very difficult, especially if it's about the future (variously attributed to Yogi Berra and Niels Bohr). Remove predicted times for stops that have passed, but first use them as a check on our estimated times.

```{r}
pre = predictions[horizon < 0, ]
pre[, estimate_error := difftime(arrival_time, estimated_time, units = "secs")]

quantile(pre$estimate_error, c(0.01, 0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975, 0.99))
```

These looks prety good - median error is 4 seconds, and almost everything within 30 seconds.

```{r}
predictions = predictions[horizon > 0 & horizon <= 120, ]
```

```{r}
predictions |>
  ggplot(aes(x = pmax(pmin(as.numeric(error), 20), -20))) +
  geom_histogram(bins = 100) +
  xlab("Prediction error, minutes\n(positive = later than predicted)") +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
```

```{r}
predictions |>
  ggplot(aes(x = pmax(pmin(as.numeric(error), 20), -20))) +
  geom_histogram(bins = 100) +
  xlab("Prediction error, minutes\n(positive = later than predicted)") +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank()) +
  facet_wrap(~horizon_cat, scales = "free_y")
```

```{r}
predictions |>
  filter(horizon < 30) |>
  mutate(error_minutes = pmax(pmin(as.numeric(error), 25), -25)) |>
  ggplot(aes(x = error_minutes)) +
  geom_histogram(bins = 100) +
  xlab("Prediction error, minutes\n(positive = later than predicted)") +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
```


```{r}
predictions |>
  filter(horizon < 7200) |>
  ggplot(aes(x = horizon / 60, y = error / 60)) +
  geom_point(pch = ".", alpha = 0.1) +
  scale_x_reverse() +
  ylim(-20, 20)
```