```{r}
library(tidyverse)
library(arrow)
library(data.table)
library(ggunc)
library(glue)

DATA_PATH = Sys.getenv("DATA_PATH")
BASE_PATH = file.path(DATA_PATH, "gotriangle")
```

```{r}
# need to set R_MAX_VSIZE=32Gb for this to work with GoTriangle
data = map(
  Sys.glob(file.path(BASE_PATH, "processed", "chunk-*.parquet")),
  \(x) read_parquet(x, col_select = c("error", "horizon", "observed_time")),
  .progress = T
) |>
  rbindlist()

units(data$error) = "mins"
units(data$horizon) = "mins"
```

## Sanity check: interpolated observed time vs. predicted for stops in the past

These should be nearly identical.

```{r}
# TODO what's going on with these big values?
quantile(
  data[horizon < 0 & !is.na(observed_time), error],
  c(0, 0.01, 0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975, 0.99, 1)
)
```

```{r}
data = data[horizon > 0 & horizon <= 60, ]
```

## Match quality

What percent matched to an arrival?

```{r}
# TODO make sure there are no NA observed times in the interpolated data
mean(!is.na(data$observed_time))
```

```{r}
data = data[!is.na(observed_time), ]
```

## Prediction quality

```{r}
data[, error_clamp20 := pmax(pmin(error, 20), -20)]
```

```{r}
data |>
  ggplot(aes(x = error_clamp20)) +
  geom_histogram() +
  xlab("Prediction error, minutes (clamped at ±20)\nLarger values are later than predicted arrivals") +
  theme(axis.text.y = element_blank(), axis.title.y = element_blank())
```

```{r}
quantile(
  data$error,
  c(0, 0.01, 0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975, 0.99, 1)
)
```

```{r}
data |>
  ggplot(aes(x = error)) +
  stat_ecdf() +
  xlab("Prediction error, minutes\nLarger values are later than predicted arrivals") +
  coord_cartesian(xlim = c(-20, 20)) +
  scale_y_continuous(breaks = (1:10) / 10, labels = scales::percent) +
  ggtitle(glue("Prediction error, cumulative distribution, GoTriangle, Jan-Apr 2026\n(n={scales::comma(nrow(data))})"))
```

### And by horizon

```{r}
data[,
  horizon_cat := ordered(
    fcase(
      horizon < 10 , "Within 10 minutes" ,
      horizon < 15 , "10-15 minutes"  ,
      horizon < 20 , "15-20 minutes"  ,
      horizon < 30 , "20-30 minutes"  ,
      horizon < 45 , "30-45 minutes"  ,
      default = "45-60 minutes"
    ),
    levels = c(
      "Within 10 minutes",
      "10-15 minutes",
      "15-20 minutes",
      "20-30 minutes",
      "30-45 minutes",
      "45-60 minutes"
    )
  )
]
```

```{r}
data |>
  ggplot(aes(x = error, color = horizon_cat)) +
  geom_vline(xintercept=0, color="black") +
  annotate("text", 0, Inf, label="Arrived earlier than predicted", hjust=1.2, vjust=1.5) +
  annotate("text", 0, -Inf, label="Arrived later than predicted", hjust=-0.2, vjust=-0.5) +
  stat_ecdf(linewidth=0.25) +
  xlab("Prediction error, minutes") +
  coord_cartesian(xlim = c(-10, 10)) +
  scale_y_continuous(breaks = (1:10) / 10, labels = scales::percent) +
  scale_x_continuous(breaks = seq.int(-10, 10, 2), labels = abs) +
  ggtitle(glue(
    "Prediction error, cumulative distribution, GoTriangle, Jan 16-Apr 11, 2026\n(n={scales::comma(nrow(data))})"
  )) +
    theme(legend.position = "bottom", axis.title.y=element_blank()) +
    scale_color_unc() +
    labs(color="Time to\npredicted arrival")
```

```{r}
ggsave("gotriangle_ecdf.png", width = 8, height = 5, dpi = 300, bg = "white")
```